### ISSUE TITLE
Not working with Logary 4.0.311

### ISSUE THREAD

**Issue by endeavour** [neoeinstein/Logary.Targets.SumoLogic#1]
I get the following runtime error when trying to use this target:

```
Unhandled exception: System.MissingMethodException: Method not found: 'Hopac.Alt`1<Microsoft.FSharp.Core.Unit> Logary.LoggerModule.log(Logary.Logger, Logary.Message)'.
   at Logary.Targets.Impl.init@196[a](SumoLogicConf conf, RuntimeInfo ri, RingBuffer`1 messages, Ch`1 shutdown, Request baseRequest, FSharpFunc`2 saveWill, FSharpOption`1 lastWill, Unit unitVar0)
   at Logary.Targets.Impl.loop[a](SumoLogicConf conf, RuntimeInfo ri, RingBuffer`1 messages, Ch`1 shutdown, FSharpFunc`2 saveWill, FSharpOption`1 lastWill)
   at Logary.Targets.SumoLogic.create@255-2.Invoke(RuntimeInfo ri, RingBuffer`1 messages, Ch`1 shutdown, FSharpFunc`2 saveWill, FSharpOption`1 lastWill)
   at Logary.Supervisor.startMinion@95(Logger logger, Ch`1 lastWillCh, MinionInfo minionInfo, FSharpOption`1 will, SupervisorState state)
   at Logary.Supervisor.loop@212-25.Do(MinionInfo x)
   at Hopac.Core.ContBind`2.DoCont(Worker& wr, X x)
   at Hopac.Ch`1.TryAlt(Worker& wr, Int32 i, Cont`1 xK, Else xE)
   at Hopac.Alt.choose@675-2.TryElse(Worker& wr, Int32 i)
   at Hopac.Alt.choose@662-1.TryElse(Worker& wr, Int32 i)
   at Hopac.Ch`1.TryAlt(Worker& wr, Int32 i, Cont`1 xK, Else xE)
   at Hopac.Alt.choose@657.DoJob(Worker& wr, Cont`1 aK)
   at Hopac.Core.Always`1.DoJob(Worker& wr, Cont`1 xK)
   at Hopac.Core.Always`1.DoJob(Worker& wr, Cont`1 xK)
   at Hopac.Core.Worker.Run(Scheduler sr, Int32 me)
No other causes.
```

**Comment by neoeinstein** [comment]
What version of `Hopac` are you using?

**Comment by endeavour** [comment]
Thanks for the quick reply. I'm using Hopac 0.3.23
